# Generated by Django 4.2.1 on 2023-05-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='firstname',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='lastname',
            new_name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='published_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
