# Generated by Django 4.2.1 on 2023-05-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_dashboard', '0002_rename_firstname_job_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
