# Generated by Django 4.2.1 on 2023-05-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_dashboard', '0003_alter_job_company_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='unique_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
